version: "3.0"
services:
  usuario-service:
    depends_on:
      dnit-usuario-db:
        condition: service_healthy
    build:
      context: .
    ports:
      - "7083:7083"
    container_name: usuario-service
    volumes:
      - ./api:/app/api
      - ./app:/app/app
      - ./test:/app/test
      - ./auth:/app/auth
    environment:
      - MODE=container
    env_file:
      - .env

  dnit-usuario-db:
    container_name: dnit-usuario-db
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: usuarioservice
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: dnit-pg-admin
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    volumes:
      - pg-admin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dnit@fga.com
      PGADMIN_DEFAULT_PASSWORD: fga1234

volumes:
  pg-data-volume:
  pg-admin-volume:
